[project]
name = "langgraph-basic"
version = "0.1.0"
description = "Basic example of langgraph"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipython>=9.12.0",
    "langchain>=1.2.15",
    "langchain-deepseek>=1.0.1",
    "langchain-tavily>=0.2.17",
    "langgraph>=1.1.6",
    "langsmith>=0.7.31",
    "openai>=2.31.0",
    "pandas>=3.0.2",
    "pulp>=3.3.0",
    "python-dotenv>=1.2.2",
    "xlrd>=2.0.2",
]
